# Generated by Django 3.1.6 on 2021-03-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carMake', models.CharField(max_length=50)),
                ('carModel', models.CharField(choices=[('Abarth', 'Abarth'), ('Alfa Romeo', 'Alfa Romeo'), ('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Bugatti', 'Bugatti'), ('Cadillac', 'Cadillac'), ('Chevrolet', 'Chevrolet'), ('Other', 'Other'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia'), ('Daewoo', 'Daewoo')], max_length=50)),
                ('carPaint', models.CharField(max_length=50)),
                ('carVin', models.CharField(max_length=17)),
                ('carMileage', models.IntegerField()),
            ],
        ),
    ]
