# Generated by Django 3.1.6 on 2021-03-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='carMake',
            field=models.CharField(choices=[('Abarth', 'Abarth'), ('Alfa Romeo', 'Alfa Romeo'), ('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Bugatti', 'Bugatti'), ('Cadillac', 'Cadillac'), ('Chevrolet', 'Chevrolet'), ('Other', 'Other'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia'), ('Daewoo', 'Daewoo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='carModel',
            field=models.CharField(max_length=50),
        ),
    ]
